### ISSUE TITLE
Uses or overrides a deprecated API

### ISSUE THREAD

**Issue by KriacoesMobile** [EricerYang/twinkle_button#1]
First thanks for amazing library help me and now my app is good with animation on buttom.

On compile show me:

Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\twinkle_button-0.0.3\android\src\main\java\com\yn\twinkle_button\TwinkleButtonPlugin.java uses or overrides a deprecated API.

You can help update or have news update soon?

**Comment by noeGnh** [comment]
You can use this:

```
twinkle_button:
    git:
      url: git@github.com:noeGnh/twinkle_button.git
      ref: develop
```
